-- ---------------------------------------------------------------------------
-- Asset Tracking schema.
--
-- This file is owned by the data platform team. The application is mapped onto
-- it and must not change it: the finance export and the insurance report both
-- read these tables directly.
--
-- It is executed once, by the PostgreSQL container, on first start.
-- ---------------------------------------------------------------------------

CREATE TABLE "AssetCategory" (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(80) NOT NULL UNIQUE,
    description VARCHAR(200)
);

CREATE TABLE assets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_tag     VARCHAR(40)   NOT NULL UNIQUE,
    name          VARCHAR(150)  NOT NULL,
    category_id   BIGINT        REFERENCES "AssetCategory"(id),
    location      VARCHAR(120)  NOT NULL,
    purchase_cost NUMERIC(12,2) NOT NULL,
    purchased_at  DATE          NOT NULL,
    status        VARCHAR(20)   NOT NULL,
    registered_at TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE asset_status_history (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id   BIGINT      NOT NULL REFERENCES assets(id),
    status     VARCHAR(20) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    note       VARCHAR(200)
);

CREATE INDEX idx_assets_status ON assets(status);
CREATE INDEX idx_history_asset ON asset_status_history(asset_id);

-- ---------------------------------------------------------------------------
-- Reference data and the assets migrated from the old spreadsheet.
-- Identifiers are carried over from the spreadsheet so that the finance export
-- keeps working, which is why they are given explicitly here.
-- ---------------------------------------------------------------------------

INSERT INTO "AssetCategory" (id, name, description) VALUES
  (1, 'Laptop',      'Portable workstations'),
  (2, 'Monitor',     'External displays'),
  (3, 'Server',      'Rack-mounted server hardware'),
  (4, 'Networking',  'Switches, routers and access points');

INSERT INTO assets (id, asset_tag, name, category_id, location, purchase_cost, purchased_at, status) VALUES
  (1, 'AST-0001', 'ThinkPad X1 Carbon',   1, 'Bengaluru HQ',    95954.20, '2024-03-11', 'IN_SERVICE'),
  (2, 'AST-0002', 'ThinkPad T14',         1, 'Bengaluru HQ',    59317.15, '2024-05-02', 'IN_SERVICE'),
  (3, 'AST-0003', 'Barco Video Wall',     2, 'Pune Office',    403452.10, '2024-06-19', 'IN_SERVICE'),
  (4, 'AST-0004', 'PowerEdge R650',       3, 'Chennai DC',     552084.40, '2023-11-28', 'IN_SERVICE'),
  (5, 'AST-0005', 'Catalyst 9300',        4, 'Chennai DC',     434002.10, '2023-09-14', 'RETIRED'),
  (6, 'AST-0006', 'MacBook Pro 14',       1, 'Pune Office',    359563.25, '2025-01-07', 'IN_REPAIR');

INSERT INTO asset_status_history (id, asset_id, status, note) VALUES
  (1, 1, 'IN_SERVICE', 'Issued to engineering'),
  (2, 2, 'IN_SERVICE', 'Issued to finance'),
  (3, 3, 'IN_SERVICE', 'Desk 4B'),
  (4, 4, 'IN_SERVICE', 'Rack 12'),
  (5, 5, 'IN_SERVICE', 'Rack 3'),
  (6, 5, 'RETIRED',    'End of support'),
  (7, 6, 'IN_SERVICE', 'Issued to design'),
  (8, 6, 'IN_REPAIR',  'Keyboard replacement');
